name: deep3d
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - opencv=3.4.2
  - pip=21.0.1
  - python=3.7.11
  - pytorch=1.7.0
  - torchaudio=0.7.0
  - torchvision=0.8.1
  - pip:
    - docstring-parser==0.12
    - jsonargparse==3.19.4
    - pytorch-lightning==1.5.1
    - pyyaml==6.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.6.0
