name: deep3d
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h0d85af4_4
  - ca-certificates=2021.9.30=hecd8cb5_1
  - cairo=1.16.0=h0ab9d94_1001
  - certifi=2021.10.8=py37hecd8cb5_0
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.1=h10f422b_1005
  - freetype=2.10.4=h4cff582_1
  - gettext=0.21.0=h7535e17_0
  - glib=2.69.1=hdf23fa2_0
  - graphite2=1.3.13=h2e338ed_1001
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hc401514_3
  - icu=58.2=h0a44026_1000
  - jasper=2.0.33=h013e400_0
  - jpeg=9d=hbcb3906_0
  - lcms2=2.11=h92f6f08_0
  - libcxx=12.0.0=h2f01273_0
  - libffi=3.3=hb1e8313_2
  - libgfortran=3.0.1=0
  - libiconv=1.16=haf1e3a3_0
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3.1=hc929b4f_1
  - libpng=1.6.37=h7cec526_2
  - libtiff=4.1.0=hcb84e12_1
  - libuv=1.40.0=haf1e3a3_0
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.12=hcdb78fc_0
  - llvm-openmp=12.0.1=hda6cdc1_1
  - lz4-c=1.9.2=h79c402e_3
  - mkl=2021.4.0=h89fa619_689
  - mkl-service=2.4.0=py37h271585c_0
  - mkl_fft=1.3.1=py37h4ab4a9b_0
  - mkl_random=1.2.2=py37hb23ed4d_0
  - ncurses=6.2=h0a44026_1
  - ninja=1.10.2=hf7b0b51_1
  - numpy=1.21.2=py37h4b4dc7a_0
  - numpy-base=1.21.2=py37he0bd621_0
  - olefile=0.46=py37_0
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1l=h0d85af4_0
  - pcre=8.45=he49afe7_0
  - pillow=8.0.0=py37h1a82f1a_0
  - pip=21.0.1=py37hecd8cb5_0
  - pixman=0.38.0=h01d97ff_1003
  - py-opencv=3.4.2=py37h7c891bd_1
  - python=3.7.11=h88f2d9e_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.7.0=py3.7_0
  - readline=8.1=h9ed2024_0
  - setuptools=58.0.4=py37hecd8cb5_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=hce871da_0
  - tbb=2021.3.0=h940c156_0
  - tk=8.6.11=h7bc2e8c_0
  - torchaudio=0.7.0=py37
  - torchvision=0.8.1=py37_cpu
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.4=h1990bb4_3
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.0
    - aiosignal==1.2.0
    - async-timeout==4.0.1
    - asynctest==0.13.0
    - attrs==21.2.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.7
    - dataclasses==0.6
    - docstring-parser==0.12
    - frozenlist==1.2.0
    - fsspec==2021.11.0
    - future==0.18.2
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.41.1
    - idna==3.3
    - importlib-metadata==4.8.2
    - jsonargparse==3.19.4
    - markdown==3.3.4
    - multidict==5.2.0
    - oauthlib==3.1.1
    - packaging==21.2
    - protobuf==3.19.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==2.4.7
    - pytorch-lightning==1.5.1
    - pyyaml==6.0
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torchmetrics==0.6.0
    - tqdm==4.62.3
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - yarl==1.7.2
    - zipp==3.6.0
